---
- name: Update playbook
  hosts: all
  become: yes
  become_method: sudo
  vars:
      state: latest
      user: bob
  tasks:
  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
